name: Deploy to Netlify

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build
        run: curl -s -X POST https://api.netlify.com/build_hooks/69a4094bc5f3036403b5c547
